### ISSUE TITLE
would you please share the paper or results of this code?

### ISSUE THREAD

**Issue by ggbox19990323** [sadPororo/AD-YOLO#1]
hi I am working on sound event localization and detection. would you please share the paper or results of this code?

**Comment by sadPororo** [comment]
Sure, you can find the paper from arXiv now, to appear in ICASSP 2023 in the future.

https://doi.org/10.48550/arXiv.2303.15703

**Comment by ggbox19990323** [comment]
thank you very much , and thank you for sharing your codes, it is very helpful to my project
